zowe/explorer-api-common

- Jenkinsfile
Signed-off-by: MarkAckert <Mark.Ackert@ca.com>
> Add Jenkinsfile only (will fail)

- explorer-api-common-test/build.gradle
- explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/exceptions/DataSetNotFoundException.java
- explorer-api-common/src/main/java/org/zowe/api/common/utils/JsonUtils.java
> updates to work with new dataset apis

- explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/ZosmfConnector.java
- explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/ZosmfProperties.java
- explorer-api-common/src/main/java/org/zowe/api/common/security/CustomUser.java
For https://github.com/zowe/jobs/issues/32
> Use different URI constructor so parameters get encoded properly

- explorer-api-common/src/main/java/org/zowe/api/common/utils/ResponseCache.java
> Add ResponseCache object

- explorer-api-common/src/main/java/org/zowe/api/common/utils/ResponseCache.java
- explorer-api-common/src/main/java/org/zowe/api/common/zosmf/services/AbstractZosmfRequestRunner.java
> zosmfservice-refactor

- explorer-api-common/src/main/java/org/zowe/api/common/utils/ResponseCache.java
> Add null check to response cache

- explorer-api-common/src/main/java/org/zowe/api/common/exceptions/HtmlEscapedZoweApiRestException.java
- explorer-api-common/src/main/java/org/zowe/api/common/exceptions/ZoweApiRestException.java
- explorer-api-common/src/main/java/org/zowe/api/common/zosmf/services/AbstractZosmfRequestRunner.java
> Add encoding to exceptions

- explorer-api-common/src/main/java/org/zowe/api/common/model/ItemsWrapper.java
- gradle.properties
> Bump version and add ItemWrapper

- explorer-api-common/src/main/java/org/zowe/api/common/zosmf/services/AbstractZosmfRequestRunner.java
Add error logging when zosmf connection fails
> Error logging

- explorer-api-common/src/main/java/org/zowe/api/common/security/SpringSecurityConfig.java
Signed-off-by: Craig-Forrest <Craig.Forrest@ibm.com>
> add logout endpoint with matcher

- .owasp-dependency-scan-suppression.xml
- gradle/versions.gradle
> update springboot and ignore test deps

- explorer-api-common/src/main/java/org/zowe/api/common/logging/UseridFilter.java
Signed-off-by: Vitek Vlcek <vitezslav@vvvlcek.info>
> added common slf filter to inject userid into log messages

- gradle.properties
> bump patch version

- Jenkinsfile
- README.md
- gradle/sonar.gradle
> migrate to sonarcloud

- Jenkinsfile
> add -SNAPSHOT if it doesn't exist

- Jenkinsfile
> version is handled in library

- Jenkinsfile
> lib changes have been merged

- Jenkinsfile
- gradle.properties
part of https://github.com/zowe/zowe-install-packaging/issues/874
> Switch to zowe artifactory

- Jenkinsfile
> Set fail build to false

- explorer-api-common-test/src/main/java/org/zowe/api/common/test/AbstractHttpIntegrationTest.java
- explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/ZosmfConnector.java
- explorer-api-common/src/main/java/org/zowe/api/common/exceptions/InvalidAuthTokenException.java
- explorer-api-common/src/main/java/org/zowe/api/common/exceptions/NoAuthTokenException.java
- explorer-api-common/src/main/java/org/zowe/api/common/utils/ResponseCache.java
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>
> zosmf return octet stream convert to b64 encoding

- explorer-api-common/src/main/java/org/zowe/api/common/security/SpringSecurityConfig.java
> Wildcard all endpoints after version in path

- explorer-api-common/src/main/java/org/zowe/api/common/security/SpringSecurityConfig.java
> Add back logout endpoint

- explorer-api-common/src/main/java/org/zowe/api/common/zosmf/services/AbstractZosmfRequestRunner.java
> Fix-processResponse not logging correctly

- explorer-api-common/src/main/java/org/zowe/api/common/connectors/zosmf/ZosmfConnectorLtpaAuth.java
- gradle.properties
> Switch ltpa auth endpoint

- gradle/versions.gradle
> Bump spring to 2.3.9

- explorer-api-common/build.gradle
- gradle/versions.gradle
> Upgrade spring security

- build.gradle
- explorer-api-common/build.gradle
- gradle/versions.gradle
> Upgrade tomcat and exclude jakarta.el

- .github/workflows/ci-tests.yml
- .github/workflows/publish-branch.yml
- .github/workflows/snapshot-release.yml
- build.gradle
- explorer-api-common-test/src/main/java/org/zowe/api/common/test/AbstractHttpIntegrationTest.java
> Allow v2.x/master to release

- .github/workflows/automatic-release.yml
- .github/workflows/specific-release.yml
> Set git config for gradle release task for v2

- .github/workflows/automatic-release.yml
- .github/workflows/snapshot-release.yml
- build.gradle
> Add zowe robot token for gradle release task

- .github/workflows/snapshot-release.yml
- .github/workflows/specific-release.yml
> Fix token used in release

- .github/workflows/automatic-release.yml
- .github/workflows/ci-tests.yml
- .github/workflows/master-into-v2-pr.yml
- .github/workflows/publish-branch.yml
- .github/workflows/snapshot-release.yml
- .github/workflows/specific-release.yml
- build timeouts
- make PR to v2 branch after commit to master
> GHA improvements

- explorer-api-common/build.gradle
- gradle/versions.gradle
> Upgrade dependencies

- explorer-api-common/build.gradle
- gradle/versions.gradle
> Upgrade logback

- explorer-api-common/build.gradle
- gradle/versions.gradle
> Upgrade spring

- explorer-api-common/src/main/java/org/zowe/api/common/zosmf/services/AbstractZosmfRequestRunner.java
> Add request and response logging
